name: Production

on:
  push:
    tags:
      - v*

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  register:
    name: Build & Register application
    runs-on: ubuntu-latest
    steps:
    - name: Get commit sha
      run: |
          echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
    - name: Use autodevops build and register
      uses: SocialGouv/actions/autodevops-build-register@v1
      with:
        environment: prod
        imagePackage: app
        token: ${{ secrets.GITHUB_TOKEN }}
        dockerbuildargs: |
            PRODUCTION=true
            GITHUB_SHA=${{ env.GITHUB_SHA }}

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [register]
    environment:
      name: production
      url: https://template.fabrique.social.gouv.fr
    steps:
    - name: Use kube-workflow deployment
      uses: SocialGouv/kube-workflow@master
      with:
        environment: prod
        token: ${{ secrets.GITHUB_TOKEN }}
        kubeconfig: ${{ secrets.KUBECONFIG }}
        rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
        rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
