name: Release

on:
  workflow_dispatch:
  push:
    branches: [master, alpha, beta, next]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - uses: SocialGouv/actions/autodevops-release@v1
      with:
        author-name: ${{ secrets.SOCIALGROOVYBOT_NAME }}
        author-email: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
        github-token: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}

